# Generated by Django 3.1 on 2020-09-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
